events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        location /api/upload {
            proxy_pass http://upload_service:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 50M;
        }

        location /api/status {
            proxy_pass http://status_service:5001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}