# this will compile all files everytime make is run
make: main.c atof.c atof.h
	gcc -o main main.c atof.c -I.

# this will clean or remove compiled files so you can start fresh
clean:
	rm -f *.o *.exe
